# -*- coding: utf-8 -*-
"""Prompt.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkValfe5ly-R_MF7Xa-JeHXssX9WO18U
"""

# 1. Install the required Groq package
!pip install groq

import os
from google.colab import userdata
from groq import Groq

# 2. Securely fetch your Groq API key from Colab Secrets
try:
    api_key = userdata.get("GROQ_API_KEY")
    client = Groq(api_key=api_key)
    print("✓ Groq client successfully initialized!")
except Exception as e:
    print("⚠️ Error loading API key. Make sure 'GROQ_API_KEY' is added to your Colab Secrets (key icon).")

# The text content we will analyze
policy_text = """
Data Retention Policy (v4.2): All customer financial transaction records must be retained
for a minimum of 7 years from the transaction date. Storage must be fully encrypted at rest
using AES-256. Access logs must be audited monthly by the security team. Unauthorized
sharing of data will result in immediate suspension.
"""

print("✓ Policy text successfully stored in memory!")

def get_summary(text, technique="zero-shot"):
    if technique == "zero-shot":
        return f"Summarize the following text into one clear sentence:\n\nText: {text}\nSummary:"
    else:  # Few-shot mode
        return f"""Task: Summarize text into one clear sentence.

Example 1 Text: Employees must complete security training annually. Failures lead to restricted access.
Example 1 Summary: Annual security training is mandatory to maintain system access.

Actual Text: {text}
Summary:"""

print("✓ Summarization template function created!")

def get_qa(text, question, technique="zero-shot"):
    if technique == "zero-shot":
        # Just ask the question directly
        return f"Context: {text}\nQuestion: {question}\nAnswer:"
    else:
        # Give 1 simple example first, then ask the question
        return f"Context: Passwords must be 12 characters.\nQuestion: What is the min length?\nAnswer: 12 characters.\n\nContext: {text}\nQuestion: {question}\nAnswer:"

print("✓ Q&A template function created simply!")

def ask_llama(prompt_text):
    # Send the prompt to the Llama 3.1 model
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt_text}],
        temperature=0.1
    )
    # Return just the text answer
    return response.choices[0].message.content

print("✓ Simple AI function is ready!")

print("--- RUNNING SUMMARIZATION TESTS ---")

# 1. Zero-shot test
zero_shot_prompt = get_summary(policy_text, technique="zero-shot")
zero_shot_result = ask_llama(zero_shot_prompt)
print("\n[Zero-shot Summary Output]:")
print(zero_shot_result)


# 2. Few-shot test
few_shot_prompt = get_summary(policy_text, technique="few-shot")
few_shot_result = ask_llama(few_shot_prompt)
print("[Few-shot Summary Output]:")
print(few_shot_result)

# 1. Remind Colab what the template is
def get_extraction_simple(text):
    return f"Extract the data retention period and encryption standard as key-value pairs:\n\nText: {text}"

# 2. Build the prompt and ask Llama
prompt_text = get_extraction_simple(policy_text)
output = ask_llama(prompt_text)

# 3. See the output
print("[Zero-shot Extraction Output]:")
print(output)

# 1. Remind Colab what the Few-shot template is (giving it 1 example)
def get_extraction_few_shot(text):
    return f"""Task: Extract key-value pairs.

Example Text: Logs are kept for 2 years. We use TLS 1.3 encryption.
Example Extraction:
- Retention Period: 2 years
- Encryption Standard: TLS 1.3

Actual Text: {text}
Extraction:"""

# 2. Build the prompt and ask Llama
prompt_text = get_extraction_few_shot(policy_text)
output = ask_llama(prompt_text)

# 3. See the output
print("[Few-shot Extraction Output]:")
print(output)

# 1. Create a simple Zero-shot Q&A prompt
def get_qa_zero_shot(text, question):
    return f"Context: {text}\nQuestion: {question}\nAnswer:"

# 2. Define our question
my_question = "What happens if someone shares data without authorization?"

# 3. Build the prompt and ask Llama
prompt_text = get_qa_zero_shot(policy_text, my_question)
output = ask_llama(prompt_text)

# 4. See the output
print("[Zero-shot Q&A Output]:")
print(output)

# 1. Create a simple Few-shot Q&A prompt with 1 short example
def get_qa_few_shot(text, question):
    return f"""Task: Answer the question briefly using the context.

Example Context: Passwords must be 12 characters minimum.
Example Question: What is the minimum password length?
Example Answer: 12 characters.

Actual Context: {text}
Actual Question: {question}
Actual Answer:"""

# 2. Define the exact same question
my_question = "What happens if someone shares data without authorization?"

# 3. Build the prompt and ask Llama
prompt_text = get_qa_few_shot(policy_text, my_question)
output = ask_llama(prompt_text)

# 4. See the output
print("[Few-shot Q&A Output]:")
print(output)